# Generated by Django 3.2 on 2023-12-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Login_details',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('your_password', models.CharField(max_length=50)),
                ('phnumber', models.CharField(default='SOME STRING', max_length=50)),
            ],
        ),
    ]
