# Generated by Django 3.2 on 2023-12-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=50)),
                ('date_and_time', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
