# Generated by Django 3.2 on 2024-02-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='your_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='phnumber',
            new_name='phone',
        ),
    ]
